name: my_recipes
description: A flutter app which show online recipes or your recipes
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  big_oven_api:
    path: packages/big_oven_api
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  local_storage:
    path: packages/local_storage
  pull_to_refresh: ^2.0.0
  recipe_repository:
    path: packages/recipe_repository
  stream_transform: ^2.0.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
