name: recipe_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: 
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.4
  json_serializable: ^6.3.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1

